geoffcheah/coach-my-swim

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss
Removed the previous button styling from banner component scss
=> Created .btn class styling. 

app/assets/stylesheets/components/_card.scss, app/controllers/lessons_controller.rb, app/policies/lesson_policy.rb, app/views/lessons/index.html.erb
Hi guys,
Let me know any thoughts ... 
Changes in lesson policy & lesson controller as. Created index view and made some styling changes for the cards. 
If we have time, maybe we can add some nice JS hover and clickable cards to replace the button - but maybe that's a Thurs / Friday job.
N.B. we didn't seed first name / last name - so "Geoff Cheah" is a placeholder - but the ruby code is there, so only take 2 seconds to dynamically change with real data.
=> Created lessons index page 

app/assets/stylesheets/components/_card.scss, app/controllers/lessons_controller.rb, app/policies/lesson_policy.rb, app/views/lessons/show.html.erb
Created the lesson card with all the relevant info.
N.B: 
- will need to change width of button component to be standard as they are different now due to text length.
- Right now the name displayed is just @lesson.email
- right now buttons do not work (still TO DO)
=> Create lesson show page

app/controllers/lessons_controller.rb, app/policies/lesson_policy.rb, app/views/lessons/edit.html.erb, app/views/lessons/show.html.erb
Hey @ap-hughes Please review code for edit and update ability in
- lessons controller update action method
- show html erb file logic for displaying the edit button
=> Creating lesson edit update actions

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_wrapper.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
It looks terrible but all i have time for :/
The images of Geoff's lovely forehead are placeholder for some appropriate icons yet to be found.
Some other minor change to banner - we will need to change the alert 'notice' at top to get rid of the blank space - left it for now.
N.B. I can't seem to center the text for the headings in each how it works 'card'...
=> Home page partly completed

app/controllers/bookings_controller.rb, app/models/user.rb, app/policies/booking_policy.rb, app/views/bookings/new.html.erb, app/views/lessons/show.html.erb, app/views/users/show.html.erb, config/routes.rb
A user can now book a coach and the booking appears on their profile page.
=> added bookings

app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/show.html.erb
Only the user and a coach that they have booked can view the user's profile page. If it is the user they can view their bookings from this page, if it is the coach they can only see the user's details and no bookings.
Needs formatting when extra profile information is available.
=> updated permissions for user profile

app/controllers/bookings_controller.rb, app/policies/booking_policy.rb, app/views/bookings/edit.html.erb, app/views/bookings/show.html.erb, config/routes.rb
Hi both,
After much trial and error - it seems to work! Thanks for the help.
Please review - the buttons do have text, but maybe we can assign global css to make the links white? 
Alex
=> Created show page and added logic for coach/swim feedback

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/users/show.html.erb, db/seeds.rb
Added first and last name to sign up form and amended the seed file to include them. Formatted profile page and booking messages on the page.
=> Update user profile information

app/controllers/pages_controller.rb, app/views/lessons/index.html.erb, app/views/pages/home.html.erb
NB> need to add images to :photo attribute of user for my code to work
=> made home lesson cards and lessons index cards clicakable

app/views/lessons/index.html.erb
Fixed the index page style issue - cards line up properly now.
=> Fixed index page style

app/models/review.rb, db/migrate/20180301120124_create_reviews.rb, db/schema.rb, test/fixtures/reviews.yml, test/models/review_test.rb
@kirstyml @ap-hughes 
Please can one of you gloss over review model just to double check it has right associations, migrations and attributes etc.
(have not created controller yet)
=> created Review model and tested in sandbox

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/controllers/lessons_controller.rb, app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/views/lessons/show.html.erb, app/views/reviews/new.html.erb, config/routes.rb, test/controllers/reviews_controller_test.rb, test/policies/review_policy_test.rb
Created: reviews controller
Put in relevant authorizations
showing each lessons reviews on its show page
=> set up whole user journey of creating a review for a lesson

app/controllers/lessons_controller.rb, app/policies/lesson_policy.rb, app/views/lessons/new.html.erb, app/views/lessons/show.html.erb
Hi both - anyone can now create a lesson. However - I still need to work on switching lesson.user.coach to true. I'm not sure I can authorize the 'save' method from this controller - maybe there is a better way?
Pushing now as having problems displaying the index page again ... having created a new lesson with a new user.
=> Added new and create lesson controllers - still work to be done

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_wrapper.scss, app/models/lesson.rb, app/views/lessons/new.html.erb
Did some styling on the simple form - let me know what you think and should be reasonably easy to apply to other sign up forms we have.
Not sure background image is right one(?). Any thoughts - good or bad - let me know.
=> Updated the form styling

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search-form.scss, app/controllers/lessons_controller.rb, app/models/lesson.rb, app/views/lessons/index.html.erb
Search works using pg_search gem. Once merged you will need to bundle install.
Can search by 
- name
- price
- ability
- speciality
=> Add search function to filter coaches

db/migrate/20180301182638_change_user_photo_default.rb, db/schema.rb, db/seeds.rb
Also added destroy reviews in db seed
=> added migration file with geoffs cloudinary url link for default photo

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_profile.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/layouts/application.html.erb, app/views/shared/_coach_messages.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_swimmer_messages.html.erb, app/views/users/show.html.erb
=> Show page css

app/assets/stylesheets/components/_profile.scss, app/views/shared/_navbar.html.erb
=> fixed footer issue

app/views/shared/_navbar.html.erb, app/views/shared/_navbar_home.html.erb
=> Homepage navbar links now working
